# -*- coding: utf-8 -*-
"""aula_exercicios_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVMPeCIHpi8sGyRQ4QnLZMzhw9mOHn0A

## Exercício 1: Verifique se um número é positivo, negativo ou zero.

 #defina um número
 #verificar se é > 0
 #> 0 -> positivo
 #< 0 -> negativo
 #caso não, 0
"""

n = float(input('Escreva um número: '))

  if n > 0:
    print('Positivo')

  elif n < 0:
    print('Negativo')

  else:
    print('Zero')

"""## Exercício 2: Peça dois números e exiba o maior.

 #Digite 2 números
 #1º numero > 2º numero -> saída: 1º número
 #1º numero < 2º numero -> saída: 2º número
 #senão, números iguais



"""

n = float(input('Escreva o 1º número: '))
m = float(input('Escreva o 2º número: '))

print('\n')

if n > m:
  print('O maior número é: ', n)
elif n < m:
  print('O maior número é: ', m)
else:
  print('Os números são iguais: ' + str(m) + ' = ' + str(n))

"""## Exercício 3: Verifique se um número é par ou ímpar.
  #Escrever um número
  #Função resto por 2
  #Se função resto = 0 -> é par
  #Senão -> é impar
"""

n = int(input('Escreva um número: '))

if (n % 2) == 0:
  print('É par')
else:
  print('É impar')

"""## Exercício 4: Verifique se um ano é bissexto.
  #Escrever o ano
  #Função ano por 4
  #Se função resto = 0 -> é bissexto
  #Senão -> não é bissexto
  
"""

ano = int(input('Escreva o ano: '))
resto = int(ano % 4)
if resto == 0:
  print('É bissexto')
else:
  print('Não é bissexto')

"""## Exercício 5: Peça três números e exiba o maior.
 #Digitar 3 numeros
 #a>b>c ou a>c>b = a
 #b>a>c ou b>c>a = b
 #c>a>b ou c>b>a = c
 #a=b=c
"""

num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))
num3 = int(input('Digite o terceiro número: '))
print('\nO maior número é', max(num1,num2,num3))

"""## Exercício 6: Verifique se um usuário pode votar (idade >= 18).
 #digite idade
 #idade >=18 -> Pode votar
 #idade < 18 -> não pode votar
"""

idade = int(input('Informe a idade: '))

if idade >= 18:
    print('Pode votar')

else:
    print('Não pode votar')

"""## Exercício 7: Verifique se já posso ir embora da aula de Análise de Dados sem assinar a folha.
 #digitar hora atual
 #ver se a hora atual >= estipulda
 #se for, pode sair
 #senão, não pode sair
"""

from datetime import datetime, time

print(datetime.now().time())
if datetime.now().time() >= time(00,45,0):
  print('Pode')
else:
  print('Não pode')

diferenca = timedelta(hours=-3)
print(diferenca)

"""## Exercício 8: Verifique se uma senha digitada corresponde a '1234'."""

senha = int(input('Digite a Senha de Login: '))
if senha == 1234:
  print('\nSenha Correta.\nO login será efetuado.')
else:
  print('\nSenha Incorreta.\nDigite novamente.')

"""## Exercício 9: Verifique se um número está entre 10 e 50."""

numero = float (input('Digite um número:'))

if (numero >= 10) and (numero < 50):
  print('\nO número está entre 10 e 50.')
else:
  print('\nO número não está entre 10 e 50.')

numero = float (input('Digite um número:'))

if 10 < numero < 50:
  print('\nO número está entre 10 e 50.')
else:
  print('\nO número não está entre 10 e 50.')

"""## Exercício 10: Peça ao usuário um número e exiba 'Alto' se for maior que 100 e 'Baixo' se for menor."""

numero = float (input('Digite um número:'))

if numero > 100:
  print('Alto')
else:
  print('Baixo')

"""## Exercício 11: Crie um menu onde o usuário pode escolher entre somar, subtrair, multiplicar e dividir dois números."""

num1 = float(input('Digite o primeiro número: '))
num2 = float(input('Digite o segundo número: '))
opcao = str(input('\nEscolha uma das operações:\n\nA - Somar\nB - Subtrair\nC - Multiplicar\nD - Dividir\n'))

if opcao == 'a' or opcao == 'A':
  soma = num1 + num2
  print('\nSoma:',soma)

elif opcao == 'b' or opcao == 'B':
  diferenca1 = num1 - num2
  diferenca2 = num2 - num1
  print('\n1ª Diferença:',diferenca1)
  print('2ª Diferença:',diferenca2)

elif opcao == 'c' or opcao == 'C':
  mult = num1 * num2
  print('\nProduto:',mult)

elif opcao == 'd' or opcao == 'D':
  quociente1 = num1 / num2 if num2 != 0 else quociente1 == 0
  quociente2 = num2 / num1 if num1 != 0 else quociente2 == 0
  print('\n1º Quociente:',quociente1)
  print('2º Quociente:',quociente2)

else:
  print('\nOpção não Encontrada. Digite A ou B ou C ou D')

def operacao(op,a,b):
  return{
      '1': a + b,
      '2': a - b,
      '3': a * b,
      '4': a / b if b != 0 else 'Divisão por zero não aceita'
  }.get(op, 'Operação inválida')

op = input('Escolha: 1-Soma, 2-Sub, 3-Mult, 4-Div: ')
a, b = map(int, input('Digite dois números: ').split())
print('Resultado: ', operacao(op, a, b))

def operacao(op,a,b):
  return{
      '1': a + b,
      '2': a - b,
      '3': a * b,
      '4': a / b
         if b != 0
         else 'Divisão por zero não aceita'
  }.get(op, 'Operação inválida')

op = input('Escolha: 1-Soma, 2-Sub, 3-Mult, 4-Div: ')
a = int(input('Digite primeiro número: '))
b = int(input('Digite segundo número: '))
print('Resultado: ', operacao(op, a, b))

"""## Exercício 12: Crie um menu para converter temperaturas entre Celsius, Fahrenheit e Kelvin."""

unidade = input('Escolha uma unidade de temperatura:\n\nC - Celsius\nF- Farenheit\nK - Kelvin\n')
temperatura = float(input('\n\nDigite a temperatura: '))

if unidade == 'c' or unidade == 'C':
   celsius = temperatura
   fahrenheit = (celsius * 9/5) + 32
   kelvin = celsius + 273.15

elif unidade == 'f' or unidade == 'F':
   celsius = (fahrenheit - 32) * (5/9)
   fahrenheit = temperatura
   kelvin = (fahrenheit - 32) * (5/9) + 273.15

elif unidade == 'k' or unidade == 'K':
   celsius = kelvin - 273.15
   fahrenheit = (kelvin - 273.15) * (9/5) + 32
   kelvin = temperatura

else:
  print('Opção inválida. Escolha C ou F ou K')

print('\n')
print('Temperatura em Celsius: ', round(celsius,1))
print('Temperatura em Fahrenheit: ', round(fahrenheit,1))
print('Temperatura em Kelvin: ', round(kelvin,1))

def converter(op, t):
  return {
      '1': (t*9/5) + 32,
      '2': t + 273.15
  }.get(op, 'Opção Inválida')

op = input('Digite a conversão desejada: 1-Celsius para Fahrenhet, 2-Celsius para Kelvin')
t = float(input('Digite a temperatura em Celsius: '))
print('Temperatura convertida: ', converter(op, t))

"""## Exercício 13: Crie um programa que traduza números de 1 a 5 para palavras (1 = um, 2 = dois...)."""

numero = int(input('Digite um número: '))
if numero == 1: print('1 = um')
elif numero == 2: print('2 = dois')
elif numero == 3: print('3 = três')
elif numero == 4: print('4 = quatro')
elif numero == 5: print('5 = cinco')
else: print('Opção inválida. Digite 1 ou 2 ou 3 ou 4 ou 5.')

op = input('Digite um número de 1 a 5: ')
print({
    '1':'um',
    '2':'dois',
    '3':'três',
    '4':'quatro',
    '5':'cinco'
}.get(op, 'Opção inválida'))

"""## Exercício 14: Crie um menu onde o usuário pode escolher entre exibir a data, hora ou sair."""

from datetime import datetime, timezone

datahora = datetime.now()
diferenca = datahora.now().timedelta(hours=-3)
fusohorario = timezone(diferenca)
datahoraatual = datahora.astimezone(fusohorario)
data = datahoraatual.now().today()
hora = datahoraatual.now().time()

opcao = input('Escolha:\n\n1 - Data Atual\n2 - Hora Atual\n3 - Sair\n')

if opcao == 1:
  print('\nData:', data)
elif opcao == 2:
  print('\nHora:', hora)
elif opcao == 3:
  exit()
else: print('Opção Inválida. Escolha 1 ou 2 ou 3')

from datetime import datetime, time, date

op = input('1-Data\n2-Hora\n3-Sair\nEscolha uma das opções: ')
print({
    '1': datetime.now().date(),
    '2': datetime.now().time(),
    '3': 'Saindo'
}.get(op, 'Opção inválida'))

from datetime import datetime, time, date

op = input('1-Data\n2-Hora\n3-Sair\nEscolha uma das opções: ')
print({
    '1': datetime.now().date(),
    '2': datetime.now().time(),
    '3': exit()
}.get(op, 'Opção inválida'))

"""## Exercício 15: Implemente um programa que identifica o dia da semana baseado em um número (1 = Segunda, 7 = Domingo)."""

numero = int(input('Digite um número: '))
if numero == 1: print('1 = segunda')
elif numero == 2: print('2 = terça')
elif numero == 3: print('3 = quarta')
elif numero == 4: print('4 = quinta')
elif numero == 5: print('5 = sexta')
elif numero == 6: print('5 = sábado')
elif numero == 7: print('5 = domingo')
else: print('Opção inválida. Digite 1 ou 2 ou 3 ou 4 ou 5 ou 6 ou 7.')

op = input('Digite um número de 1 a 7: ')
print({
    '1':'segunda',
    '2':'terça',
    '3':'quarta',
    '4':'quinta',
    '5':'sexta',
    '6':'sábado',
    '7':'domingo'
}.get(op, 'Opção inválida'))

"""## Exercício 16: Verifique se um número é par ou ímpar usando if ternário."""

n = int(input('Escreva um número: '))
resto = (n % 2)

resultado = "É par" if resto == 0 else "É ímpar"
print(resultado)

"""## Exercício 17: Verifique se um número é positivo ou negativo usando if ternário."""

n = float(input('Escreva um número: '))

resultado = "É posito" if n > 0 else "É negativo" if n < 0 else "Neutro"
print(resultado)

"""## Exercício 18: Retorne 'Adulto' se a idade for maior ou igual a 18, senão 'Menor de idade'."""

idade = int(input('Informe a idade: '))
if idade >= 18: print('Adulto')
else: print('Menor Idade')

idade = int(input('Informe a idade: '))
resultado = 'Adulto'if idade >= 18 else 'Menor Idade'
print(resultado)

"""## Exercício 19: Verifique se um número é maior que 100 e retorne 'Grande' ou 'Pequeno'."""

numero = float (input('Digite um número:'))
if numero > 100: print('Grande')
else: print('Pequeno')

numero = float (input('Digite um número:'))
resultado = 'Grande' if numero > 100 else 'Pequeno'
print(resultado)

"""## Exercício 20: Retorne 'Aprovado' se a nota for maior ou igual a 7, senão 'Reprovado'."""

nota = float (input('Digite a nota:'))
if 7 <= nota <= 10: print('Aprovado')
elif 0 <= nota < 7: print('Reprovado')
else: print('Valor Inválido')

nota = float(input('Digite a nota: '))
resultado = 'Aprovado' if 7 <= nota <= 10 else 'Reprovado' if 0 <= nota < 7 else 'Valor Inválido'
print(resultado)

"""## Exercício 21: Imprima os números de 1 a 10 usando um laço for."""

vetor = []
for X in range(1,11):
    vetor = (vetor + [X])
print(vetor)

for i in range(1,11):
    print(i)

"""## Exercício 22: Imprima os números pares de 1 a 20."""

vetor = []
for X in range(2,22,2):
    vetor = (vetor + [X])
print(vetor)

for i in range(0, 21, 2):
  if i != 0:
    print(i)

for i in range(2, 21,2):
    print(i)

"""## Exercício 23: Calcule a soma dos números de 1 a 100."""

vetor = []
for X in range(1,101):
    vetor = (vetor + [X])
    soma = sum(vetor)
print(soma)

"""## Exercício 24: Imprima a tabuada do 5."""

vetor = []
X = int(input('Digite um número máximo para ser multiplicado na tabuada de 5 : '))
for X in range(0,X + 1):
    mult = 5 * X
    print('5 x', X, '=', mult)

"""## Exercício 25: Imprima os 10 primeiros números da sequência de Fibonacci."""

def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

# Example usage
for i in range(10):
    print(fibonacci(i), end=" ")

"""## Exercício 26: Percorra uma string e imprima cada caractere."""

fruta = "banana"
for letra in fruta:
    print(letra)

fruta = "banana"
indice = 0
while indice < len(fruta):
    letra = fruta[indice]
    print(letra)
    indice += 1

"""## Exercício 27: Crie um programa que peça um número e imprima sua contagem regressiva até 0."""

contador = int(input('Digite um número máximo para a contagem regressiva: '))
while contador >= 1:
    print(contador)
    contador -= 1
print(contador)

contador = int(input('Digite um número máximo para a contagem regressiva: '))
for i in range(contador, -1, -1):
    print(i)

"""## Exercício 28: Crie um programa que solicite 5 números ao usuário e exiba a soma deles."""

a = float(input('Digite o primeiro número: '))
b = float(input('Digite o segundo número: '))
c = float(input('Digite o terceiro número: '))
d = float(input('Digite o quarto número: '))
e = float(input('Digite o quinto número: '))

soma = sum([a,b,c,d,e])
print("\nSOMA: ",soma)

"""## Exercício 29: Imprima todas as vogais de uma string digitada pelo usuário."""

texto = input('Digite um texto: ')
for letra in texto:
  if letra in 'aeiouAEIOUáéíóúÁÉÍÓÚãõÃÕâêîôûÂÊÎÔÛÀà':
    print(letra)

"""## Exercício 30: Crie um programa que peça 5 números e exiba apenas os números pares."""

numeros = [5]
for i in range(5):
    numeros.append(int(input('Digite um número: ')))

print('\n')
for numero in numeros:
  if numero % 2 == 0:
    print(numero)

"""## Exercício 31: Percorra uma lista de frutas e imprima cada uma."""

frutas = ["maçã", "banana", "laranja", "uva", "pêra", "tucumã"]

for fruta in frutas:
    print(fruta)

"""## Exercício 32: Some todos os números de uma lista."""

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
soma = sum(numeros)
print(soma)

"""## Exercício 33: Multiplique cada número de uma lista por 2 e imprima o resultado."""

numeros = [5]
for i in range(5):
    numeros.append(int(input('Digite um número: ')))

print('\n')
for numero in numeros:
  mult = numero * 2
  print(str(numero) + " X " + str(2) + " = " + str(mult))

"""## Exercício 34: Conte quantas palavras existem em uma lista de palavras."""

lista_de_palavras = ['ola', 'mundo', 'em programação', 'em python']
numero_de_palavras = len(lista_de_palavras)
print("Número de palavras:", numero_de_palavras)

"""## Exercício 35: Imprima cada letra de uma palavra separadamente."""

palavra = "Palácio"
lista_letras = list(palavra)
print(lista_letras)

"""## Exercício 36: Crie uma lista com 5 números e imprima o maior."""

numeros = [5]
for i in range(5):
    numeros.append(int(input('Digite um número: ')))

print('\n')
print('Maior número:',max(numeros))

"""## Exercício 37: Crie uma lista e inverta a ordem dos elementos."""

lista = []
for i in range(5):
    lista.append(str(input('Digite uma palavra: ')))
lista.reverse()
print('\nLista Invertida:\n')
print(lista)

"""## Exercício 38: Crie uma lista com 5 nomes e remova o último nome."""

lista = ['azul', 'verde', 'ocre', 'cinza', 'violeta']
lista.remove('violeta')
print(lista)

"""## Exercício 39: Ordene uma lista de números."""

numeros = [10]
for i in range(10):
    numeros.append(float(input('Digite um número: ')))

print('\n')
numeros.sort()
print('Lista em Ordem Crescente: ',numeros)

"""## Exercício 40: Crie uma lista com 5 números e exiba apenas os pares."""

numeros = [5]
for i in range(5):
    numeros.append(int(input('Digite um número: ')))

print('\n')
par = [i for i in numero if i % 2 == 0]
print('Números Pares:',par)

"""## Exercício 41: Crie uma lista e adicione um novo elemento no final."""

minha_lista = [0,1,2,3]
   minha_lista += [4,5,6,7,8,9,10]
   print(minha_lista)

"""## Exercício 42: Verifique se um número existe dentro de uma lista."""

lista = [1, 2, 3, 4, 5]

verificar = float(input('Digite um número: '))

if verificar in lista:
    print('O número ' + str(verificar) + ' está na lista.')
else:
    print('O número ' + str(verificar) + ' não está na lista.')

"""## Exercício 43: Crie uma lista de números e calcule a média."""

numeros = [7]
for i in range(7):
    numeros.append(float(input('Digite um número: ')))

media = sum(numeros) / len(numeros)
print('\n')
print('Média: ',round(media,3))

"""## Exercício 44: Crie uma lista de nomes e converta todos para maiúsculas."""

lista = []
for i in range(5):
    lista.append(str(input('Digite uma palavra: ')))
    lista[i] = lista[i].upper()

print('\n')
print(lista)

"""## Exercício 45: Crie uma lista de números e remova os duplicados."""

lista = []
for i in range(8):
    lista.append(float(input('Digite um número: ')))
    lista_sem_duplicatas = list(set(lista))

print('\n')
print(lista_sem_duplicatas)

"""## Exercício 46: Crie um dicionário com nomes de alunos e suas notas e exiba a nota de um aluno específico."""

# Criação do dicionário com nomes de alunos e suas notas
notas_alunos = {
    "João": 8.5,
    "Maria": 9.2,
    "José": 7.8,
    "Ana": 10.0
}

# Escolhe um nome de aluno para buscar a nota
nome_aluno = str(input('Digite o nome do aluno: '))

# Verifica se o nome do aluno existe no dicionário
if nome_aluno in notas_alunos:
    # Se existir, imprime a nota do aluno
    print('A nota de ' +str(nome_aluno) + ' é: ' + str(notas_alunos[nome_aluno]))
else:
    # Se não existir, informa que o aluno não foi encontrado
    print('Aluno ' + str(nome_aluno) + ' não encontrado no dicionário.')

"""## Exercício 47: Adicione um novo aluno e sua nota a um dicionário."""

notas_alunos = {
    "João": 8.5,
    "Maria": 9.2,
    "José": 7.8,
    "Ana": 10.0
}
notas_alunos['Carlos'] = 8.5
notas_alunos['Lúcia'] = 9.2
notas_alunos['Pedro'] = 7.8
notas_alunos['Fernanda'] = 10.0
print(notas_alunos)

"""## Exercício 48: Remova um aluno do dicionário."""

notas_alunos = {
    "João": 8.5,
    "Maria": 9.2,
    "José": 7.8,
    "Ana": 10.0
}
notas_alunos.pop('Maria')
print(notas_alunos)

"""## Exercício 49: Percorra um dicionário e imprima suas chaves e valores."""

pessoa = {'nome': 'Estebán', 'altura': 1.76, 'idade': 21}
print(pessoa)

"""## Exercício 50: Verifique se uma chave existe no dicionário."""

pessoa = {'nome': 'Estebán', 'altura': 1.76, 'idade': 21}
pessoa['nome'] = str(input('Digite o nome: '))
print('\n')

if pessoa['nome'] == 'Estebán':
    print(pessoa)
else:
    print(str(pessoa['nome']) + ' não foi encontrado no dicionário.')